var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                             m  ",
   "                                                   oo             xxx           ",
   "                                             ll    xx     xxx    xx!xx          ",
   "                                    o o      xx            v     x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                                                                          x  ",
   "  x                 xxxxx                xxxxx        o                   s  x  ",
   "  x                 x   x                                                    x  ",
   "  x  @              x   x    l     o                                         x  ",
   "  xxxxxxxxxxxxxxxxxxx   xxxxxxx   xxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxx  ",
   "                              x   x                  x       x                  ",
   "                              x!!!x                  x!!!!!!!x                  ",
   "                              x!!!x                  x!!!!!!!x                  ",
   "                              xxxxx                  xxxxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                                                                   x!x  ",
   "                                      x!!x                                                                   x!x  ",
   "                                      x!!xxxxxxxxxx                                                          x!x  ",
   "                                      xx!!!!!!!!!!xx                                                         x!x  ",
   "                                       xxxxxxxxxx!!x                                                        mx!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x   xxxx xxxx                     =!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   | lxx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                              xxxxxxxxx                        xxxx!!!!!xxxx                                      ",
   "                             x!!!!!!!!!xxx   xxx     xxx          xxxxxxx        xxx         xxx                  ",
   "                             x!!!xxx!!!x       x     x                           x x         x x                  ",
   "                              xxxvvvxxx        x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               l     o       xxx     xxx      x      x              x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x     xxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x  sxxx             x                    ",
   "     @       x         x        x   x        s x     x               x   xxxxx               x                    ",
   "    xxxxxxxxxx   xxx   x        x   x        xxx     x               x           xxxxxx      x                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!x       xx o xx         xo    x               x     o     x x         x                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xx  xxxxx  xx xx  o o  xx                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!x    o                 xx!!!!!!xx !      xllx   x!!x   xx     xx                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!x                     xx!!!!!!xx  !      xxxx   xxxx    xxxxxxx                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!xx   l         xxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!xxxxxxxxxxxxxxxxxxxxxx!!!!!xx    !                                                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                   xxx               xxx                                      ",
   "                                                                                                              ",
   "                                        x                  xxxxx                                              ",
   "                                       x!x                                                                    ",
   "                                      x!!!x                !!!        !!!  xxx                             x  ",
   "                                     x!!!!!x               !x!        !x!                                  x  ",
   "                                    x!!!!!!!xxx             x!!!!!!!!!!x                                   x  ",
   "                                     x!!!!!x                x!!!!!!!!!!x       xxx                         x  ",
   "                                      x!!!x                 x!!!!!!!!!!x      x!!!x=                       x  ",
   "                                      x!!!x                 xxxxxxxxxxxx       xxx        xxx              x  ",
   "                      x           =xxxx!!!xx      x   x    sxx                                             x  ",
   "                      x               x!!!xxxxxxxxx   xxxxxxxx              x x                            x  ",
   "                      x      xx       x!!!x           x                    x!!!x=                          x  ",
   "                      x               x!!!x        xxxx                     xxx                            x  ",
   "                      x=            xxx!!!xx     xx   x                                                    x  ",
   "                      x               x!!!x= = = =    x            xxx                                     x  ",
   "                      x      xx       x!!!x           x           x!!!x=                                   x  ",
   "                      x               x!!!x    = = = =x   s        xxx       xxx                           x  ",
   "                      x             =xx!!!xx     ll   xxxxxxx               x!!!x                          x  ",
   "                      x       o   o   x!!!x      xx   x!!!!!x                xxv        xxx                x  ",
   "                                      x!!!x           x!!!!!xxxxxxxxxx                 x!!!x             m x  ",
   "                             xxx xxxxxxx!xxx     o o  x!!!!!!!!!!!!!!x                   vx                x  ",
   "                             x  x       x  x          x!!!!!!!!!!!!!!x                                     x  ",
   "                             x          v  x   xxxxxxxxxxxvxxxxxxxxxxxxxx                                  x  ",
   "                          xxxxx           xx                                         xxx        xxx        x  ",
   "                              x     x                                               x!!!x                xxx  ",
   "xxx                           x    xxx                                               xxx                 x x  ",
   "  x          s      o         x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                      xxx    x  ",
   "  x                 x                     x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                x x             o o    x=                           o x         xxx                     x  ",
   "  x               x   x       xx          x                             xxx       x!!!x          x         x  ",
   "  x              xxxxxxx      x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                 x         xxxxxxxxxxxxx  x    x    x    x    x     xx xx                    xxx        x  ",
   "  x    ll@ll        x         x           x!!xllllx!!!!xllllx!!!!xllllxx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
   "    x                                                                   x                                     ",
   "    x    x   x    xxx    x   x     x       x   x    x     x    x  x     x                                     ",
   "    x     x x    x   x   x   x     x   x   x   x    x x   x    x  x     x                                     ",
   "    x      x     x   x   x   x      x  x  x    x    x   x x             x                                     ",
   "    x      x      xxx     xxx        xx xx     x    x     x    x  x     x                                     ",
   "    x @                                                                 x                                     ",
   "!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
